added emr hadoop module
alibabacloud-automation/terraform-alicloud-emr-hadoop pull request #1
Opened 2020-01-13 09:55 UTC by qiyinfei

2020-01-14 03:47 UTC, Lexsss commented on README.md
> +# terraform-alicloud-emr-hadoop
Refer to README.md in [RDS module](https://registry.terraform.io/modules/terraform-alicloud-modules/rds/alicloud/2.0.1)

2020-01-14 03:47 UTC, Lexsss commented on example/outputs.tf
> +  value = module.emr-hadoop.emr_cluster_id
description

2020-01-14 03:47 UTC, Lexsss commented on example/outputs.tf
> +output "emr_hadoop_id" {
更多outputs

2020-01-14 03:47 UTC, Lexsss commented on main.tf
> +  cluster_type          = "HADOOP"
是否应传入？我理解后期会支持其他集群类型

2020-01-14 03:47 UTC, Lexsss commented on main.tf
> +provider "alicloud" {
根目录的 main.tf 中应开放需要开放的所有参数，以支持所有类型集群，不需要将具体配置写入这个 tf 中。

2020-01-14 03:47 UTC, Lexsss commented on outputs.tf
> +output "emr_cluster_id" {
description

2020-01-14 03:47 UTC, Lexsss commented on README.md
> +## Inputs
不需要写 inputs 和 outputs

2020-01-14 03:52 UTC, qiyinfei commented on main.tf
> +  cluster_type          = "HADOOP"
这个应该是必传的，这个repository针对的就是hadoop的，和箫竹讨论过，他说每个产品类型一个module

2020-01-14 06:03 UTC, qiyinfei commented on main.tf
> +  cluster_type          = "HADOOP"
> 是否应传入？我理解后期会支持其他集群类型

这个应该是必传的，这个repository针对的就是hadoop的，和箫竹讨论过，他说每个产品类型一个module

2020-01-15 06:54 UTC, xiaozhu36 requested changes

2020-01-15 06:54 UTC, xiaozhu36 commented on README-CN.md
> +2. 将阿里云账户的AK和EMR集群实例运行所在的区设置到环境变量中:
usage第二步不需要，直接展示上面的代码就行

2020-01-15 06:54 UTC, xiaozhu36 commented on README-CN.md
> +Created and maintained by He Guimin(@xiaozhu36, heguimin36@163.com)
可以把你自己的信息也写上

2020-01-15 06:54 UTC, xiaozhu36 commented on variables.tf
> +  default = "ABCtest1234!"
默认值设置为 YourPassword123

2020-01-15 06:54 UTC, xiaozhu36 commented on variables.tf
> +  default = true
开启高可用是否意味着要多个vswitch

2020-01-15 06:54 UTC, xiaozhu36 commented on main.tf
> +}
在emr的module中没必要创建新的vpc，vsw和security group，这些都应该直接通过参数传递进来

2020-01-15 06:54 UTC, xiaozhu36 commented on main.tf
> +  configuration_source = "terraform-alicloud-modules/emr-hadoop"
provider中要支持的参数应该和其他的保持一致，比如：https://github.com/terraform-alicloud-modules/terraform-alicloud-ecs-instance/blob/master/main.tf#L1

2020-01-15 06:54 UTC, xiaozhu36 commented on example/main.tf
> +module "emr-hadoop" {
example中的如果用到vpc，vsw和安全组，可以直接调用vpc和security group的module来做，可以看下：https://github.com/terraform-alicloud-modules/terraform-alicloud-ecs-instance/blob/master/examples/basic/main.tf#L53

2020-01-15 06:54 UTC, xiaozhu36 commented on main.tf
> +  name     = var.ram_name
如果role对与emr是必须的，那么这个resource的参数可以不用暴露出去，直接写死就好了，比如:
name = "ram-role-for-emr-hadoop", 但是由于ram role在一个账号下不能重复，可以使用 random resource，生成一个随机的字段，可以参考下：https://github.com/terraform-alicloud-modules/terraform-alicloud-autoscaling/blob/master/locals.tf#L2

2020-01-15 06:54 UTC, xiaozhu36 commented on main.tf
> +  description = "this is a role test."
描述最好写清楚场景，而不是直接写test

2020-01-15 06:54 UTC, xiaozhu36 commented on main.tf
> +  host_group {
我理解host group应该是一个列表，既然这样，就应该以列表的方式传递进来，然后内部通过dynamic进行解析，可以参看下：https://github.com/terraform-alicloud-modules/terraform-alicloud-ecs-instance/blob/master/main.tf#L28

2020-01-15 06:54 UTC, xiaozhu36 commented on main.tf
> +    instance_type     = data.alicloud_emr_instance_types.default.types.0.id
通过这几个data source获取到的值都应该对外暴露出来一个参数，允许客户自己指定，如果客户没有指定，再由datasoure获取

2020-01-15 06:55 UTC, xiaozhu36 requested changes

2020-01-15 06:55 UTC, xiaozhu36 commented on main.tf
> +  emr_ver      = "EMR-3.24.0"
如果由多个版本，那么这个emr ver应该以一个参数的方式暴露出来

2020-01-15 07:55 UTC, qiyinfei commented on variables.tf
> +  default = true
> 开启高可用是否意味着要多个vswitch

不用的，这个开启高可用，是保证master至少有两个节点

2020-01-20 07:07 UTC, xiaozhu36 requested changes

2020-01-20 07:07 UTC, xiaozhu36 commented on example/main.tf
> +  is_open_public_ip = true
example中要把所需要的vpc，vswitch，安全组等都创建并加上

2020-01-20 07:07 UTC, xiaozhu36 commented on example/outputs.tf
> +output "host_group_instance_type" {
所有的output前面都需要加一个 `this_`，比如`this_host_group_instance_type `

2020-01-20 07:07 UTC, xiaozhu36 commented on main.tf
> +}
这个没改

2020-01-20 07:07 UTC, xiaozhu36 commented on variables.tf
> +variable "option_software_list" {
所有的参数都需要加上 `type`，比如：
```
variable "charge_type" {
  description = "The instance charge type. Valid values: Prepaid and Postpaid. Default to Postpaid."
  type = string
  default = "PostPaid"
}
```

2020-01-20 09:24 UTC, xiaozhu36 requested changes

2020-01-20 09:24 UTC, xiaozhu36 commented on variables.tf
> +variable "module_name" {
这个参数是干啥的

2020-01-20 09:24 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
磁盘的参数最好都给个default值

2020-01-20 09:24 UTC, xiaozhu36 commented on variables.tf
> +  default     = "PostPaid"
这个我理解应该是 PrePaid和PostPaid吧

2020-01-20 09:24 UTC, xiaozhu36 commented on main.tf
> +}
在主module main.tf  中，不需要创建新的vpc和security group，直接通过vpc_id 和 security_group_id来传递就行

2020-01-20 09:24 UTC, xiaozhu36 commented on variables.tf
> +  default     = "EMR-3.24.0"
如果hadoop有多个版本，那么需要再加一个modules，吧每个版本单独指定下。具体的可以看看rds或者redis的

2020-01-20 09:24 UTC, xiaozhu36 commented on variables.tf
> +      disk_count        = "4"
这几个默认值是官方推荐的默认值么？

2020-01-20 09:43 UTC, qiyinfei commented on variables.tf
> +      disk_count        = "4"
> 这几个默认值是官方推荐的默认值么？

是的，控制台创建默认也是这些值

2020-01-20 09:44 UTC, qiyinfei commented on variables.tf
> +  default     = "PostPaid"
> 这个我理解应该是 PrePaid和PostPaid吧

是的，Valid values: 已改过来了

2020-01-20 09:46 UTC, qiyinfei commented on variables.tf
> +  default     = ""
> 磁盘的参数最好都给个default值

磁盘的数量和类型是动态查出来的，每个用户能配置的都不一样

2020-02-11 06:50 UTC, qiyinfei commented on variables.tf
> +variable "module_name" {
已删除

2020-02-14 03:19 UTC, zql-tqy commented on README-CN.md
> +本 Module 用于在阿里云的 VPC 下创建一个[E-MapReduce](https://help.aliyun.com/document_detail/28068.html).
这个地址应该不是产品的，再看一下应该是product的

2020-02-14 03:19 UTC, zql-tqy commented on README-CN.md
> +本模板要求使用版本 Terraform 0.12.
本模版要求使用 Terraform 0.12 和 阿里云 Provider 1.56.0+。
（自查：1.56.0是默认的版本，如果需要其他版本，自行更改）

2020-02-14 03:19 UTC, zql-tqy commented on README-CN.md
> +用法
改成 ##+空格+用法

2020-02-14 03:19 UTC, zql-tqy commented on README-CN.md
> +  master_pwd = "YourPassword123!"
这个module进行格式化后再粘贴过来

2020-02-14 03:19 UTC, zql-tqy commented on README-CN.md
> +* 本 Module 使用的 AccessKey 和 SecretKey 可以直接从 `profile` 和 `shared_credentials_file` 中获取。如果未设置，可通过下载安装 [aliyun-cli](https://github.com/aliyun/aliyun-cli#installation) 后进行配置.
把中文readme中的标点都换成中文标点

2020-02-14 03:19 UTC, zql-tqy commented on README-CN.md
> +Created and maintained by Qi yinfei(@yfqi, qiyf_shadow@yeah.net)
Created and maintained by Qi yinfei(@yfqi, qiyf_shadow@yeah.net), He Guimin(@xiaozhu36, heguimin36@163.com)

2020-02-14 03:19 UTC, zql-tqy commented on README.md
> +This module requires Terraform 0.12.
The Module requires Terraform 0.12 and Terraform Provider AliCloud 1.56.0+.

2020-02-14 03:19 UTC, zql-tqy commented on example/main.tf
> +  vswitch_id = data.alicloud_vswitches.all.ids.0
进行一下格式化

2020-02-24 02:38 UTC, qiyinfei commented on README-CN.md
> +本 Module 用于在阿里云的 VPC 下创建一个[E-MapReduce](https://help.aliyun.com/document_detail/28068.html).
我看rds中都是写的产品的地址呢，如果不行的话，那这句话就不要了？

2020-02-24 02:38 UTC, qiyinfei commented on README-CN.md
> +本 Module 用于在阿里云的 VPC 下创建一个[E-MapReduce](https://help.aliyun.com/document_detail/28068.html).
> 这个地址应该不是产品的，再看一下应该是product的

我看rds中都是写的产品的地址呢，如果不行的话，那这句话就不要了？

2020-02-24 07:38 UTC, zql-tqy commented on README-CN.md
> +
留一个空行就行，多余的去掉吧
下面 hcl那个下面不用留空行

2020-02-24 07:38 UTC, zql-tqy commented on README-CN.md
> +  master_pwd               = "YourPassword123!"
这个module中如果有不同资源的参数，加个空行隔开

2020-02-24 07:38 UTC, zql-tqy commented on README-CN.md
> +
中英文的readme中，这个位置要加一些东西，参考https://github.com/terraform-alicloud-modules/terraform-alicloud-slb/blob/master/README-CN.md

2020-02-24 07:38 UTC, zql-tqy commented on README.md
> +This module requires Terraform 0.12.
这个地方还是没有加provider的版本

2020-02-24 07:38 UTC, zql-tqy commented on main.tf
> +  version                 = ">=1.69.0"
以后这个参数去掉了

2020-02-24 07:38 UTC, zql-tqy commented on outputs.tf
> +  description = "The supported mount data disk type of this emr cluster host group"
建议以后value和description调整一下顺序，description中都加上结束标点

2020-02-24 09:18 UTC, xiaozhu36 requested changes

2020-02-24 09:18 UTC, xiaozhu36 commented on outputs.tf
> +  value       = alicloud_emr_cluster.default.*.id
这个module只创建一个cluster，所以，返回的参数应该返回一个string，而不是list
`value       = concat(alicloud_emr_cluster.default.*.id, [""])[0]`
其他的参数也一样

2020-02-24 11:59 UTC, xiaozhu36 requested changes

2020-02-24 11:59 UTC, xiaozhu36 commented on README-CN.md
> +本 Module 用于在阿里云的 VPC 下创建一个[E-MapReduce](https://help.aliyun.com/document_detail/28068.html)。
要说清楚这个module主要是基于emr来创建一个hadoop 集群

2020-02-24 11:59 UTC, xiaozhu36 commented on example/main.tf
> +data "alicloud_emr_main_versions" "default" {
example 改为 examples
example下不要直接写 tf文件，而是要再建一个目录，如 examples/complete，然后把所有的文件移动到 complete下面

2020-02-24 11:59 UTC, xiaozhu36 commented on main.tf
> +  name     = "terraform-ram-role-${random_uuid.this.result}"
`name     = "substr("tf-ram-role-for-hadoop-${replace(random_uuid.this.result, "-", "")}", 0, 32)"

2020-02-24 11:59 UTC, xiaozhu36 commented on main.tf
> +  name         = "terraform-test-hadoop-module"
这个name参数应该暴露出去

2020-02-24 11:59 UTC, xiaozhu36 commented on outputs.tf
> +  description = "The role id used to launch one or more instances."
这个描述不太对吧

2020-02-24 11:59 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_emr_cluster" "default" {
这个地方要加一个 create 的开关，当 create是true的时候，才创建集群
同时这个开关也要应用到ram role上

2020-02-25 15:14 UTC, zql-tqy commented on variables.tf
> +  description = "The host group of ecs mount disk type to create emr cluster instance. Supported value: cloud,cloud_efficiency,cloud_ssd,local_disk,cloud_essd."
所有的英文描述标点后面空一格cloud, cloud_efficiency, cloud_ssd, local_disk, cloud_essd.
这里面的描述最后标点都补齐吧

2020-02-25 15:14 UTC, zql-tqy commented on main.tf
> +  name         = "terraform-test-hadoop-module"
这个参数还是没有暴露出去，这个应该开放变量让用户填写，不填写的我们提供这个作为默认值

2020-02-25 15:14 UTC, zql-tqy commented on main.tf
> +  name     = substr("tf-ram-role-for-hadoop-${replace(random_uuid.this.result, "-", "")}", 0, 32)
这个name也开放变量，如果用户不填写，再使用我们生成的作为name

2020-02-25 15:14 UTC, zql-tqy commented on examples/complete/main.tf
> +
在example中设置变量region和profile，调用security_group module的时候也要传这两个变量，readme中的module也要写上这两个变量

2020-02-27 07:38 UTC, zql-tqy commented on README-CN.md
> +
这个里面把region和profile加上，和上面的一样

2020-02-27 07:38 UTC, zql-tqy commented on README-CN.md
> +  source  = "alibaba/security-group/alicloud"
资源放在第一个参数位置吧

2020-02-27 08:11 UTC, xiaozhu36 requested changes

2020-02-27 08:11 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_emr_cluster" "default" {
把default 改为 this

2020-02-27 08:11 UTC, xiaozhu36 commented on variables.tf
> +  description = "The switch to control creation of the emr cluster or not."
create_instance  改为 create

2020-02-27 08:11 UTC, xiaozhu36 commented on variables.tf
> +variable "sys_disk_type" {
sys_disk_type 改为 system_disk_type

2020-02-27 08:11 UTC, xiaozhu36 commented on variables.tf
> +variable "sys_disk_capacity" {
sys_disk_capacity 改为 system_disk_capacity

2020-02-27 08:11 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
如果这个emr_version必须得填写的话，最好给一个你们推荐的default

2020-02-27 08:44 UTC, xiaozhu36 approved these changes

2020-02-27 08:44 UTC, merged